version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
          GOSUMDB: "off"
          GOPROXY: "direct"
    working_directory: /go/src/github.com/3almadmon/MailboxService
    steps:
      - checkout
      - run: go version
      - run:
          name: "fetch dependencies"
          command: |
            go env
            go mod download
      - run: make test-race
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip make
            pip install awscli
      - run: make docker-build
      - run: make push-ecr

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main