tag: prod

server:
  type: grpc
  host: localhost
  port: 50060
  deadline: 10 # 10s

database:
  messages:
    type: dynamodb
    tablename: mailboxsvc-prod
    pagination:
      pagesize: 25
      maxresultcount: 120

cognito:
  userpoolid: eu-west-1_PgGsriGNl
  clientid: 3tlflae0aqg4jpn3r476hqv92i
  region: eu-west-1

storage:
  type: s3
  bucket: fatmalabidi-configs
  credentialspath: mailboxsvc/config-prod.json