apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailbox-svc-dev
spec:
  selector:
    matchLabels:
      app: mailbox-svc-dev
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: mailbox-svc-dev
        tier: backend
    spec:
      containers:
        - name: mailbox-svc-dev
          image: 966715539404.dkr.ecr.eu-west-1.amazonaws.com/fatmalabidi/mailbox-svc:0.0.0
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: AWS_DEFAULT_REGION
              value: "eu-west-1"
            - name: CONFIGOR_ENV
              value: development
          ports:
            - containerPort: 50060
              protocol: TCP

